### ISSUE TITLE
Missing: BTS Catalog!

### ISSUE THREAD

**Issue by ungoldman** [CodeForPortland/data#1]
The link to the Bureau of Technology Services data catalog is dead (was http://www.portlandoregon.gov/bts/article/268487). I haven't been able to find the catalog anywhere else... anyone seen it or know anything about it?

/cc @pdxmele @fardog @elauervose @bcomnes @anomalily @chrissm07

(Ran into this trying to track down as many housing data sources as possible for http://github.com/codeforportland/housing)

**Comment by ungoldman** [comment]
Update: @Caged found this issue a while back (last September!) and never got a response from Ben Berry (PDX CTO) https://twitter.com/Caged/status/569648204112797696

**Comment by caged** [comment]
Pure speculation, but I fear they've rolled it all into civicapps, which unfortunately, is cumbersome and buggy and a bit of a ghost town compared to its enthusiastic launch days.  Most of the data can be found directly through the FTP site at [ftp://ftp02.portlandoregon.gov/CivicApps/](ftp://ftp02.portlandoregon.gov/CivicApps/).  I also maintain a visual index of many of the same datasets here: https://github.com/caged/portland-atlas.  Finally, there is a [data index](http://www.portlandmaps.com/metadata/index.cfm?&layerid=52099&action=DisplayLayerList) on portlandmaps.com, but it's the metadata-only with no direct links to the dataset (you have to hunt around for it).

**Comment by ksmpdx** [comment]
Believe your speculation is correct. We (City of Portland) rolled that data into civicapps a while back. Good news is that we are working on a new version that will hopefully be less cumbersome, support multiple formats and apis, etc. Goal is to follow with a renewed push to open up a lot more of the data you see on the [portlandmaps metadata page](http://www.portlandmaps.com/metadata/index.cfm?&layerid=52099&action=DisplayLayerList), as well as other stuff. Apologies for the interim hassles. Trying to kick the ghosts out and bring some life back in. Stay tuned.

**Comment by ungoldman** [comment]
Thanks @ksmpdx. We (@CodeForPortland) are very interested in helping with any piece of the puzzle (for free). Feel free to reach out anytime -- ungoldman@gmail.com
